export default CategoriaEvento = [
  { key: 1, value: "Familiar." },
  { key: 2, value: "Comunidad y cultura." },
  { key: 3, value: "Caridad y otras causas." },
  { key: 4, value: "Carros, botes y aeronáutica." },
  { key: 5, value: "Cine, medios y entretenimiento." },
  { key: 6, value: "Gobierno y política." },
  { key: 7, value: "Salud y bienestar." },
  { key: 8, value: "Pasatiempo, hobbies e intereses especiales." },
  { key: 9, value: "Música." },
  { key: 10, value: "Artes escénicas." },
  { key: 11, value: "Moda y belleza." },
  { key: 12, value: "Comida y bebidas." },
  { key: 13, value: "Hogar y estilo de vida." },
  { key: 14, value: "Actividades escolares." },
  { key: 15, value: "Educación." },
  { key: 16, value: "Ciencia y tecnología." },
  { key: 17, value: "Deportes y fitness." },
  { key: 18, value: "Viajes y actividades al aire libre." },
  { key: 18, value: "Festividad y actividades de temporada." },
];
