export default [
  {
    Id: "1",
    Titulo: "Festival de baile",
    NombreOrganizador: "Tatiana Muñoz",
    CalificacionOrganizador: 4,
    EventosRealizadorOrg: 6,
    ExpOrganizador: 50,
    CorreoAnfitrion: "ejemplo@gmail.com",
    CelularAnfitrion: "+ 57 3200987654",
    Imagen: require("../assets/Ejemplo.jpg"),
    Fecha: "Jul 02 del 2024 - 6:00 P.M",
    Ubicacion: "Medellin - Antioquia",
    FechaInicio: "24/06/2024",
    FechaFin: "24/06/2024",
    HoraFin: "5:00 P.M",
    HoraInicio: "9:00 A.M",
    Categoria: "Reunión Social",
    Aforo: "100 Personas",
    TipoLugar: "Salón social",
    ClaseEvento: "Publico - presencial",
    AforoDisponible: "100 Personas",
    Descripcion:
      "Lorem ipsum dolor sit amet consectetur. Nibh et ultricies amet iaculis a semper placerat. Vitae fringilla massa imperdiet elementum in dignissim fringilla amet lectus.",
  },
];
