const EventType = [
  { value: 1, label: "Ceremonia" },
  { value: 2, label: "Fiesta, reunión social o encuentro" },
  { value: 3, label: "Cena o Gala" },
  { value: 4, label: "Canto o presentación musical" },
  { value: 5, label: "Concierto, actuacion, teatro" },
  { value: 6, label: "Stand up comedy" },
  { value: 7, label: "Conferencia" },
  { value: 8, label: "Convención" },
  { value: 9, label: "Congreso" },
  { value: 10, label: "Cumbre" },
  { value: 11, label: "Debate" },
  { value: 12, label: "Premiación" },
  { value: 13, label: "Recorrido o Tour" },
  { value: 14, label: "Campamento, viaje o retiro" },
  { value: 15, label: "Capacitación, curso o entrenamiento" },
  { value: 16, label: "Seminario o charla" },
  { value: 17, label: "Festival o feria" },
  { value: 18, label: "Reunión o evento de networking" },
  { value: 19, label: "Feria comercial, feria de consumidores o exposición" },
  { value: 20, label: "Juego o evento deportivo" },
  { value: 21, label: "Carrera o evento de resistencia" },
  { value: 22, label: "Torneo" },
  { value: 23, label: "Otro. Cual?" },
];
