export default TipoLugar = [
  { key: 1, value: "Casa" },
  { key: 2, value: "Apartamento" },
  { key: 3, value: "Salon comunal" },
  { key: 4, value: "Salon para eventos" },
  { key: 5, value: "Hotel" },
  { key: 6, value: "Resort o complejo vacacional" },
  { key: 7, value: "Restaurante" },
  { key: 8, value: "Roof Top bar/restaurante" },
  { key: 9, value: "Finca recreacional" },
  { key: 10, value: "Hacienda o casas grandes" },
  { key: 11, value: "Bar" },
  { key: 12, value: "Discoteca" },
  { key: 13, value: "Iglesia" },
  { key: 14, value: "Escuela" },
  { key: 15, value: "Auditorio" },
  { key: 16, value: "Sala de junta" },
  { key: 17, value: "Salones de fiesta." },
  { key: 18, value: "Comedor corporativo." },
  { key: 19, value: "Centro de conferencias." },
  { key: 20, value: "Centro de negocios." },
  { key: 21, value: "Centro comunitario." },
  { key: 22, value: "Centro de convenciones." },
  { key: 23, value: "Galería de arte." },
  { key: 24, value: "Sede académica" },
  { key: 25, value: "Estadio o coliseo." },
  { key: 26, value: "Teatro" },
  { key: 27, value: "Cine" },
  { key: 28, value: "Oficina" },
  { key: 29, value: "Parque" },
  { key: 30, value: "Bosque" },
  { key: 31, value: "Museo" },
  { key: 32, value: "Monumento" },
  { key: 33, value: "Centro cultural" },
  { key: 34, value: "Cancha deportiva" },
  { key: 35, value: "Centro acuático" },
  { key: 36, value: "Roof garden" },
  { key: 37, value: "Terrazas" },
  { key: 38, value: "Jardines" },
  { key: 39, value: "Librería" },
  { key: 40, value: "Zona arqueológicas" },
  { key: 41, value: "Circo" },
  { key: 42, value: "Salones privado." },
  { key: 43, value: "Spa" },
  { key: 44, value: "Playa" },
  { key: 45, value: "Viñedo" },
  { key: 46, value: "Fábrica antigua" },
  { key: 47, value: "Plaza de toros" },
  { key: 48, value: "Construcción histórica" },
  { key: 49, value: "Barco" },
  { key: 50, value: "Casino" },
  { key: 51, value: "Otro (Cual?)" },
];
